name: "Draft: Build & Deploy to GitHub Pages"

# This workflow supports both manual runs and automatic runs on push to master.
# It requires the repository secret `GH_PAGES_TOKEN` (preferred) or will fallback to GITHUB_TOKEN.
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        run: npm run build:prod

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN || secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          keep_files: false
